gemini:
  api_key: ${{ secrets.GIT_KEY }}
  api_url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

app:
  max_file_size: 10485760

  allowed_types: ["pdf", "docx"]
